//Template created by Alex Usbergo
//https://github.com/alexdrone

import UIKit

extension UIFont {
    func inconicFontOfSize(size: CGFloat) -> UIFont {
        return UIFont(name: "IconicFont", size: size)
    }
}

enum IconicFontGlyph: String {

  case airplay = "\uf100"
  case alarm = "\uf101"
  case attachment = "\uf102"
  case balance = "\uf103"
  case banner = "\uf104"
  case basketball = "\uf105"
  case battery = "\uf106"
  case bell = "\uf107"
  case bookmark = "\uf108"
  case box = "\uf109"
  case brightness = "\uf10a"
  case business = "\uf10b"
  case calc = "\uf10c"
  case calendar = "\uf10d"
  case camera = "\uf10e"
  case cart = "\uf10f"
  case chat = "\uf110"
  case chat2 = "\uf111"
  case check = "\uf112"
  case clock = "\uf113"
  case cloud = "\uf114"
  case cloudReload = "\uf115"
  case coffee = "\uf116"
  case configure = "\uf117"
  case contact = "\uf118"
  case creditCard = "\uf119"
  case cube = "\uf11a"
  case cup = "\uf11b"
  case db = "\uf11c"
  case diplay = "\uf11d"
  case dots = "\uf11e"
  case download = "\uf11f"
  case edit = "\uf120"
  case envelope = "\uf121"
  case envelopeClose = "\uf122"
  case envelopeMail = "\uf123"
  case fastForward = "\uf124"
  case file = "\uf125"
  case files = "\uf126"
  case flag = "\uf127"
  case flash = "\uf128"
  case folder = "\uf129"
  case folderClosed = "\uf12a"
  case gift = "\uf12b"
  case grid = "\uf12c"
  case home = "\uf12d"
  case inbox = "\uf12e"
  case info = "\uf12f"
  case lightbulb = "\uf130"
  case like = "\uf131"
  case location = "\uf132"
  case lockClose = "\uf133"
  case lockOpen = "\uf134"
  case magnet = "\uf135"
  case map = "\uf136"
  case memo = "\uf137"
  case minus = "\uf138"
  case mirror = "\uf139"
  case mute = "\uf13a"
  case options = "\uf13b"
  case pen = "\uf13c"
  case phone = "\uf13d"
  case photo = "\uf13e"
  case piechart = "\uf13f"
  case play = "\uf140"
  case playlist = "\uf141"
  case plus = "\uf142"
  case printer = "\uf143"
  case questionMark = "\uf144"
  case quicklook = "\uf145"
  case radio = "\uf146"
  case reader = "\uf147"
  case record = "\uf148"
  case refresh = "\uf149"
  case repeat = "\uf14a"
  case reply = "\uf14b"
  case resize = "\uf14c"
  case rewind = "\uf14d"
  case ruller = "\uf14e"
  case search = "\uf14f"
  case send = "\uf150"
  case settings = "\uf151"
  case sleep = "\uf152"
  case star = "\uf153"
  case timeMachine = "\uf154"
  case timer = "\uf155"
  case timer2 = "\uf156"
  case torchlight = "\uf157"
  case trash = "\uf158"
  case trash2 = "\uf159"
  case umbrella = "\uf15a"
  case upload = "\uf15b"
  case volume = "\uf15c"
  case web = "\uf15d"
  case window = "\uf15e"
}
